Added rake instructions as dependency installation fails without
If the rake gem is missing when the dependency installation procedure is triggered by running `/bin/setup`, it exits with the following error:

```
Building native extensions.  This could take a while...
ERROR:  Error installing rainbow:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/rainbow-2.2.2/ext
/usr/bin/ruby2.3 mkrf_conf.rb

current directory: /var/lib/gems/2.3.0/gems/rainbow-2.2.2/ext
/usr/bin/ruby2.3 -rubygems /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake RUBYARCHDIR=/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.2 RUBYLIBDIR=/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.2
/usr/bin/ruby2.3: No such file or directory -- /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake (LoadError)
```
Fixing that error requires `$ gem install rake` to be launched on the command line. Then, installing dependencies works as expected:

```
Bundle complete! 11 Gemfile dependencies, 30 gems now installed.
```
I added a corresponding instruction to the _Development_ section to make sure the presence of rake is checked beforehand.